(function () {
  const clone = (value) => JSON.parse(JSON.stringify(value));
  let draft = clone(window.VOLOKNO_DEFAULTS);
  const $ = (selector) => document.querySelector(selector);
  const status = $('#save-status');
  const setStatus = (message, color = '') => { if (status) { status.textContent = message; status.style.color = color; } };
  const set = (path, value) => { const keys = path.split('.'); const last = keys.pop(); const target = keys.reduce((item, key) => item[key], draft); target[last] = value; };
  const get = (path) => path.split('.').reduce((value, key) => value?.[key], draft);
  const makeField = (labelText, key, value, kind = 'text', placeholder = '') => {
    const label = document.createElement('label'); label.textContent = labelText; const input = document.createElement(kind === 'textarea' ? 'textarea' : 'input'); if (kind !== 'textarea') input.type = kind; else input.rows = 3; input.value = value || ''; input.dataset.serviceField = key; if (placeholder) input.placeholder = placeholder; label.append(input); return label;
  };
  const changed = () => setStatus('Есть несохранённые изменения', '#b66b32');
  const render = () => {
    document.querySelectorAll('[data-field]').forEach((field) => { field.value = get(field.dataset.field) || ''; });
    $('#image-preview img').src = draft.hero.image;
    const serviceFields = $('#service-fields');
    serviceFields.replaceChildren(...draft.services.items.map((item, index) => {
      const box = document.createElement('div'); box.className = 'service-editor'; const kicker = document.createElement('div'); kicker.className = 'card-index'; kicker.textContent = 'УСЛУГА ' + String(index + 1).padStart(2, '0'); const heading = document.createElement('div'); heading.className = 'service-editor-heading'; const name = document.createElement('h3'); name.textContent = item.name || 'Новая услуга'; const remove = document.createElement('button'); remove.className = 'remove-service'; remove.type = 'button'; remove.dataset.removeService = index; remove.textContent = 'Удалить'; heading.append(name, remove);
      const nameField = makeField('Название', index + '.name', item.name); const descField = makeField('Описание', index + '.description', item.description, 'textarea'); const priceField = makeField('Цена или условие', index + '.price', item.price); box.append(kicker, heading, nameField, descField, priceField); return box;
    }));
    const contactFields = $('#contact-fields');
    contactFields.replaceChildren(...(draft.contact.items || []).map((item, index) => {
      const box = document.createElement('div'); box.className = 'service-editor contact-editor'; const heading = document.createElement('div'); heading.className = 'service-editor-heading'; const kicker = document.createElement('div'); kicker.className = 'card-index'; kicker.textContent = 'КОНТАКТ ' + String(index + 1).padStart(2, '0'); const remove = document.createElement('button'); remove.className = 'remove-service'; remove.type = 'button'; remove.dataset.removeContact = index; remove.textContent = 'Удалить'; heading.append(kicker, remove);
      const label = makeField('Название поля', index + '.label', item.label); const value = makeField('Значение', index + '.value', item.value); const href = makeField('Ссылка или действие', index + '.href', item.href, 'text', 'https://... или tel:+7...'); [label, value, href].forEach((wrapper) => { const field = wrapper.querySelector('input, textarea'); delete field.dataset.serviceField; field.dataset.contactField = index + '.' + (wrapper === label ? 'label' : wrapper === value ? 'value' : 'href'); }); const hint = document.createElement('small'); hint.textContent = 'Оставьте #, если это просто текст без перехода.'; href.append(hint); box.append(heading, label, value, href); return box;
    }));
    document.querySelectorAll('[data-field]').forEach((field) => field.addEventListener('input', (event) => { set(event.currentTarget.dataset.field, event.currentTarget.value); changed(); }));
    document.querySelectorAll('[data-service-field]').forEach((field) => field.addEventListener('input', (event) => { const [index, key] = event.currentTarget.dataset.serviceField.split('.'); draft.services.items[Number(index)][key] = event.currentTarget.value; const heading = event.currentTarget.closest('.service-editor')?.querySelector('h3'); if (heading && key === 'name') heading.textContent = event.currentTarget.value || 'Новая услуга'; changed(); }));
    document.querySelectorAll('[data-contact-field]').forEach((field) => field.addEventListener('input', (event) => { const [index, key] = event.currentTarget.dataset.contactField.split('.'); draft.contact.items[Number(index)][key] = event.currentTarget.value; changed(); }));
  };
  const showPanel = (name) => { document.querySelectorAll('[data-panel]').forEach((panel) => panel.classList.toggle('is-visible', panel.dataset.panel === name)); document.querySelectorAll('[data-tab]').forEach((button) => button.classList.toggle('is-active', button.dataset.tab === name)); $('#page-title').textContent = ({ overview: 'Обзор сайта', hero: 'Главный экран', services: 'Услуги и цены', contacts: 'Контакты' })[name]; };
  const api = async (url, options = {}) => { const response = await fetch(url, { credentials: 'same-origin', ...options }); if (!response.ok) { const error = new Error('HTTP ' + response.status); error.status = response.status; throw error; } return response; };
  const load = async () => { const response = await api('/api/content', { headers: { Accept: 'application/json' } }); draft = window.normalizeVoloknoContent(await response.json()); render(); setStatus('Все изменения сохранены', '#318e77'); };
  const showLogin = () => { $('#login-panel').hidden = false; $('#admin-content').hidden = true; };
  const showAdmin = () => { $('#login-panel').hidden = true; $('#admin-content').hidden = false; };
  const init = async () => {
    try { await api('/api/auth/me'); showAdmin(); await load(); } catch (error) { if (error.status === 401) showLogin(); else { showLogin(); $('#login-error').textContent = 'Сервер пока недоступен. Попробуйте ещё раз.'; } }
  };
  $('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); $('#login-error').textContent = ''; const button = event.currentTarget.querySelector('button'); button.disabled = true; try { await api('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: $('#login-username').value.trim(), password: $('#login-password').value }) }); showAdmin(); await load(); event.currentTarget.reset(); } catch (error) { $('#login-error').textContent = error.status === 401 ? 'Неверный логин или пароль.' : 'Не удалось выполнить вход.'; } finally { button.disabled = false; } });
  $('#logout-button').addEventListener('click', async () => { try { await api('/api/auth/logout', { method: 'POST' }); } finally { showLogin(); } });
  document.querySelectorAll('[data-tab], [data-tab-jump]').forEach((button) => button.addEventListener('click', () => showPanel(button.dataset.tab || button.dataset.tabJump)));
  $('#add-service').addEventListener('click', () => { if (draft.services.items.length >= 50) return setStatus('Можно добавить не более 50 услуг', '#b34a3c'); draft.services.items.push({ name: '', description: '', price: 'По запросу' }); render(); changed(); $('#service-fields .service-editor:last-child input')?.focus(); });
  $('#service-fields').addEventListener('click', (event) => { const button = event.target.closest('[data-remove-service]'); if (!button) return; if (draft.services.items.length === 1) return setStatus('Должна остаться хотя бы одна услуга', '#b34a3c'); draft.services.items.splice(Number(button.dataset.removeService), 1); render(); changed(); });
  $('#add-contact').addEventListener('click', () => { if (draft.contact.items.length >= 30) return setStatus('Можно добавить не более 30 полей', '#b34a3c'); draft.contact.items.push({ label: '', value: '', href: '#' }); render(); changed(); $('#contact-fields .contact-editor:last-child input')?.focus(); });
  $('#contact-fields').addEventListener('click', (event) => { const button = event.target.closest('[data-remove-contact]'); if (!button) return; if (draft.contact.items.length === 1) return setStatus('Должно остаться хотя бы одно контактное поле', '#b34a3c'); draft.contact.items.splice(Number(button.dataset.removeContact), 1); render(); changed(); });
  $('#save-button').addEventListener('click', async () => { const button = $('#save-button'); button.disabled = true; try { const response = await api('/api/content', { method: 'PUT', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(draft) }); draft = window.normalizeVoloknoContent(await response.json()); render(); setStatus('Изменения опубликованы', '#318e77'); } catch (error) { setStatus(error.status === 401 || error.status === 403 ? 'Сессия истекла. Войдите снова.' : 'Не удалось сохранить изменения', '#b34a3c'); if (error.status === 401) showLogin(); } finally { button.disabled = false; } });
  $('#image-upload').addEventListener('change', async (event) => { const file = event.target.files?.[0]; if (!file) return; const allowed = new Set(['image/png', 'image/jpeg', 'image/webp']); if (!allowed.has(file.type) || file.size > 5 * 1024 * 1024) { setStatus('Выберите PNG, JPG или WebP размером до 5 МБ', '#b34a3c'); event.target.value = ''; return; } const form = new FormData(); form.append('file', file); try { const response = await api('/api/uploads', { method: 'POST', body: form }); draft.hero.image = (await response.json()).url; $('#image-preview img').src = draft.hero.image; changed(); } catch (error) { setStatus('Изображение не удалось загрузить или декодировать', '#b34a3c'); } finally { event.target.value = ''; } });
  init();
})();
